### ISSUE TITLE
Data Out of Date

### ISSUE THREAD

**Issue by lilleymatthew** [kateto/covidstates#1]
The website indicates new waves of the Survey Data (e.g. governor approval in Report #22).
However, the new data waves haven't been added to the /State/ folder (no update since Wave 9)
/Report Data/Report 22 Approval/ does contain limited information but much less rich than is available for each previous wave in the /State/ folder.

**Comment by kateto** [comment]
The executive approval data we currently have is now available through our State Behavior Dashboard:
https://lazerlab.shinyapps.io/Behaviors_During_COVID/
Dataset download is available on the front page, state charts are in the Executive Approval tab. Data in the dashboard is likely to be more frequently updated than the tables on GitHub.
